name: vidis
description: Vidis Flutter version

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

scripts:
  start:
    dev: "flutter run --dart-define=ENV=dev"
    prod: "flutter run --dart-define=ENV=prod"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dio: ^4.0.6
  time_machine: ^0.9.17
  json_annotation: ^4.0.1
  provider: ^6.0.0
  openid_client: ^0.4.6
  jwt_decode: ^0.3.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - 'assets/icons/icon.png'
    - 'assets/logo.png'

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages